### PR TITLE
Gameplay: Adding the ability to attack cancel movement options

### PR DESCRIPTION
**Pull request by HeatXD**
Air Dash Into Attack Cancels
Run Into Attack Cancels
HighJump Into Attack Cancels

### CODE REVIEW

**Comment by HeatXD** [comment]
Should this option be behind a toggle? Or is it fine like this? lmk!

**Comment by panthavma** [comment]
As we said on discord, it's good! I'll get to merging this once next version is out

**Comment by HeatXD** [comment]
My code created here is released under MIT license.
So do whatever you want with it :)

**Comment by panthavma** [comment]
Thank you for your contribution !

**Pull request merged**
